import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const cssPath = resolve(import.meta.dirname, '../../styles/gui2.css')
const routePath = resolve(import.meta.dirname, '../Gui2HomeRoute.jsx')
const css = readFileSync(cssPath, 'utf8')
const routeSource = readFileSync(routePath, 'utf8')

const posterRailBlock = css.match(/\.gui2-homev2-poster-rail\s*\{[^}]+\}/)
const continueRailBlock = css.match(/\.gui2-homev2-continue-rail\s*\{[^}]+\}/)
const continueViewportBlock = css.match(/\.gui2-homev2-continue-viewport\s*\{[^}]+\}/)
const continueTrackBlock = css.match(/\.gui2-homev2-continue-track\s*\{[^}]+\}/)
const continueReadingBandBlock = css.match(/\.gui2-homev2-band-continue-reading\s*\{[^}]+\}/)
const continueReadingCardBlock = css.match(/\.gui2-homev2-band-continue-reading\s+\.gui2-homev2-continue\s*\{[^}]+\}/)
const recentThumbBlock = css.match(/\.gui2-homev2-recent-thumb\s*\{[^}]+\}/)
const recentRowBlock = css.match(/\.gui2-homev2-recent-row\s*\{[^}]+\}/)
const recentRailBlock = css.match(/^\s*\.gui2-homev2-recent-rail\s*\{[^}]+\}/m)
const recentFeatureBlock = css.match(/^\s*\.gui2-homev2-recent-feature\s*\{[^}]+\}/m)
const recentFeatureCopyBlock = css.match(/^\s*\.gui2-homev2-recent-feature-copy\s*\{[^}]+\}/m)
const heroSwitchBlock = css.match(/^\s*\.gui2-homev2-hero-switch\s*\{[^}]+\}/m)
const heroBodyBlock = css.match(/^\s*\.gui2-homev2-hero-body\s*\{[^}]+\}/m)
const heroMetaRowBlock = css.match(/^\s*\.gui2-homev2-hero-meta-row\s*\{[^}]+\}/m)
const heroTitleLongBlock = css.match(/^\s*\.gui2-homev2-hero-title\.is-long\s*\{[^}]+\}/m)
const laneTabsBlock = css.match(/\.gui2-homev2-lane-tabs\s*\{[^}]+\}/)
const laneShellBlock = css.match(/\.gui2-homev2-lane-shell\s*\{[^}]+\}/)
const laneArrowBlock = css.match(/\.gui2-homev2-lane-arrow\s*\{[^}]+\}/)
const laneTrackBlock = css.match(/\.gui2-homev2-lane-track\s*\{[^}]+\}/)
const laneViewportBlock = css.match(/\.gui2-homev2-lane-viewport\s*\{[^}]+\}/)
const laneTabActiveBlock = css.match(/\.gui2-homev2-lane-tab\.active\s*\{[^}]+\}/)
const modeTabsBlock = css.match(/\.gui2-homev2-mode-tabs\s*\{[^}]+\}/)
const modeTabActiveBlock = css.match(/\.gui2-homev2-mode-tab\.active\s*\{[^}]+\}/)
const heroRecentBlock = css.match(/^\s*\.gui2-homev2-hero-recent\s*\{[^}]+\}/m)
const stageGridBlock = css.match(/^\s*\.gui2-homev2-stage-grid\s*\{[^}]+\}/m)
const stageMainBlock = css.match(/^\s*\.gui2-homev2-stage-main\s*\{[^}]+\}/m)
const heroStageBlock = css.match(/^\s*\.gui2-homev2-stage\s*\{[^}]+\}/m)
const stageBandBlock = css.match(/^\s*\.gui2-homev2-stage-band\s*\{[^}]+\}/m)
const stageAfterBlock = css.match(/^\s*\.gui2-homev2-stage::after\s*\{[^}]+\}/m)
const stageOverlayBlock = css.match(/^\s*\.gui2-homev2-stage-overlay\s*\{[^}]+\}/m)
const homeStackBlock = css.match(/^\s*\.gui2-homev2-stack\s*\{[^}]+\}/m)
const homeContentBlock = css.match(/\.gui2-shell\[data-route='home'\] \.gui2-content\s*\{[^}]+\}/)
const homeTopbarBlock = css.match(/\.gui2-shell\[data-route='home'\] \.gui2-topbar\s*\{[^}]+\}/)
const immersiveHomeTopbarOverrideBlock = css.match(/\.gui2-shell\[data-shell-variant='immersive'\]\[data-route='home'\] \.gui2-topbar\s*\{[^}]+\}/m)
const posterOverlayBlock = css.match(/\.gui2-homev2-poster-overlay\s*\{[^}]+\}/)
const posterChipBlock = css.match(/\.gui2-homev2-poster-chip\s*\{[^}]+\}/)
const posterPopBlock = css.match(/\.gui2-homev2-poster-pop\s*\{[^}]+\}/)
const posterHitareaBlock = css.match(/\.gui2-homev2-poster-hitarea\s*\{[^}]+\}/)
const loadingRecentRowBlock = css.match(/\.gui2-homev2-loading-recent-row\s*\{[^}]+\}/)
const loadingPosterRailBlock = css.match(/\.gui2-homev2-loading-poster-rail\s*\{[^}]+\}/)
const navGroupSharedBlock = css.match(/\.gui2-nav-group,\s*\.gui2-nav-footer\s*\{[^}]+\}/)
const navFooterBlocks = [...css.matchAll(/^\s*\.gui2-nav-footer\s*\{[^}]+\}/gm)]
const navFooterBlock = navFooterBlocks.find((block) => block[0].includes('margin-top: auto'))
const heroTransitionImageBlock = css.match(/\.gui2-homev2-stage\.transitioning \.gui2-homev2-stage-image,[^}]+\}/)

assert.ok(posterRailBlock, 'poster rail CSS block should exist')
assert.ok(continueRailBlock, 'continue rail CSS block should exist')
assert.ok(continueViewportBlock, 'continue viewport CSS block should exist')
assert.ok(continueTrackBlock, 'continue track CSS block should exist')
assert.ok(continueReadingBandBlock, 'manga continue reading band CSS block should exist')
assert.ok(continueReadingCardBlock, 'manga continue reading cards should keep a dedicated footprint')
assert.ok(recentThumbBlock, 'recent thumb CSS block should exist')
assert.ok(recentRowBlock, 'recent row CSS block should exist')
assert.ok(recentRailBlock, 'recent rail CSS block should exist')
assert.ok(recentFeatureBlock, 'recent feature CSS block should exist')
assert.ok(recentFeatureCopyBlock, 'recent feature copy CSS block should exist')
assert.ok(heroSwitchBlock, 'hero switch CSS block should exist')
assert.ok(heroBodyBlock, 'hero body CSS block should exist')
assert.ok(heroMetaRowBlock, 'hero meta row CSS block should exist')
assert.ok(heroTitleLongBlock, 'long hero title CSS block should exist')
assert.ok(laneTabsBlock, 'lane tabs CSS block should exist')
assert.ok(laneShellBlock, 'lane shell CSS block should exist')
assert.ok(laneArrowBlock, 'lane arrow CSS block should exist')
assert.ok(laneTrackBlock, 'lane track CSS block should exist')
assert.ok(laneViewportBlock, 'lane viewport CSS block should exist')
assert.ok(laneTabActiveBlock, 'active lane tab CSS block should exist')
assert.ok(modeTabsBlock, 'home mode tabs CSS block should exist')
assert.ok(modeTabActiveBlock, 'active home mode tab CSS block should exist')
assert.ok(heroRecentBlock, 'hero recent CSS block should exist')
assert.ok(stageGridBlock, 'stage grid CSS block should exist')
assert.ok(stageMainBlock, 'stage main CSS block should exist')
assert.ok(heroStageBlock, 'hero stage CSS block should exist')
assert.ok(stageBandBlock, 'stage band CSS block should exist')
assert.ok(stageAfterBlock, 'hero stage bottom fade CSS block should exist')
assert.ok(stageOverlayBlock, 'hero stage overlay CSS block should exist')
assert.ok(homeStackBlock, 'home stack CSS block should exist')
assert.ok(homeContentBlock, 'home content shell CSS block should exist')
assert.ok(homeTopbarBlock, 'home topbar CSS block should exist')
assert.ok(immersiveHomeTopbarOverrideBlock, 'immersive home topbar override CSS block should exist')
assert.ok(posterOverlayBlock, 'poster overlay CSS block should exist')
assert.ok(posterChipBlock, 'poster chip CSS block should exist')
assert.ok(posterPopBlock, 'poster pop CSS block should exist')
assert.ok(posterHitareaBlock, 'poster hitarea CSS block should exist')
assert.ok(loadingRecentRowBlock, 'loading recent row CSS block should exist')
assert.ok(loadingPosterRailBlock, 'loading poster rail CSS block should exist')
assert.ok(navGroupSharedBlock, 'shared nav group/footer CSS block should exist')
assert.ok(navFooterBlock, 'sidebar footer CSS block should exist')
assert.ok(heroTransitionImageBlock, 'hero transition CSS block should exist')
assert.ok(!posterRailBlock[0].includes('justify-content: space-between'), 'poster rail should not space cards apart')
assert.ok(!continueRailBlock[0].includes('justify-content: space-between'), 'continue rail should not space cards apart')
assert.ok(posterRailBlock[0].includes('justify-content: start'), 'poster rail should pack cards from the left')
assert.ok(continueRailBlock[0].includes('justify-content: start'), 'continue rail should pack cards from the left')
assert.ok(posterRailBlock[0].includes('repeat(7, minmax(0, 1fr))'), 'poster rail should keep a fixed seven-slot desktop rhythm instead of stretching short pages')
assert.ok(continueRailBlock[0].includes('repeat(6, minmax(0, 1fr))'), 'continue rail should keep six desktop slots per page')
assert.ok(continueViewportBlock[0].includes('overflow: hidden'), 'continue viewport should clip the off-screen pages')
assert.ok(continueTrackBlock[0].includes('transition:'), 'continue track should animate page changes')
assert.ok(continueReadingBandBlock[0].includes('gap: 12px'), 'manga continue reading band should keep the premium row spacing')
assert.ok(continueReadingCardBlock[0].includes('min-height: 336px'), 'manga continue reading cards should stay tall enough to read like a featured return rail')
assert.ok(loadingPosterRailBlock[0].includes('repeat(7, minmax(0, 1fr))'), 'home loading shelves should mirror the seven-slot desktop browse rhythm')
assert.ok(recentRailBlock[0].includes('display: grid'), 'recent rail should become a compact vertical companion next to the hero')
assert.ok(recentFeatureBlock[0].includes('display: grid'), 'recent feature should exist as the rotating live recent surface')
assert.ok(recentFeatureCopyBlock[0].includes('position: absolute'), 'recent lead item copy should live inside the art instead of forming a separate block')
assert.ok(heroSwitchBlock[0].includes('position: absolute'), 'hero switch should float inside the hero rather than living inside a separate panel')
assert.ok(heroBodyBlock[0].includes('align-content: end'), 'hero body should resolve into one bottom-anchored editorial stack')
assert.ok(heroMetaRowBlock[0].includes('display: flex'), 'hero meta chips should live in a compact inline row')
assert.ok(heroTitleLongBlock[0].includes('-webkit-line-clamp: 3'), 'long hero titles should gain an extra line before truncation')
assert.ok(laneTabsBlock[0].includes('display: inline-flex'), 'category lanes should expose light inline tabs instead of boxed selectors')
assert.ok(laneTabsBlock[0].includes('overflow-x: auto'), 'lane tabs should browse horizontally instead of wrapping into static lines')
assert.ok(laneShellBlock[0].includes('position: relative'), 'lane shell should anchor the new carousel controls')
assert.ok(laneArrowBlock[0].includes('position: absolute'), 'lane carousel arrows should float over the row for smooth paging')
assert.ok(laneViewportBlock[0].includes('overflow: hidden'), 'category lane viewport should clip inactive tab slides cleanly')
assert.ok(laneTrackBlock[0].includes('520ms'), 'category lanes should animate with a slower premium horizontal transition')
assert.ok(laneTabActiveBlock[0].includes('background:'), 'active category tab should receive a visible inline state')
assert.ok(modeTabsBlock[0].includes('display: inline-flex'), 'home mode tabs should read like a compact control bar')
assert.ok(modeTabActiveBlock[0].includes('background:'), 'active home mode tab should get a dedicated surface treatment')
assert.ok(heroRecentBlock[0].includes('height: 100%'), 'recent companion should be trapped to the stage height')
assert.ok(heroRecentBlock[0].includes('overflow: hidden'), 'recent companion should clip its own content instead of stretching the whole top row')
assert.ok(stageGridBlock[0].includes('grid-template-columns: minmax(0, 1fr) 308px'), 'stage grid should dedicate a narrow fixed rail to recently updated')
assert.ok(stageMainBlock[0].includes('grid-template-rows: auto 1fr'), 'stage main column should separate top markers from the editorial copy stack')
assert.ok(stageBandBlock[0].includes('margin-top: calc(var(--gui2-topbar-h) * -1)'), 'top stage should bleed upward under the topbar instead of stopping short below it')
assert.ok(stageAfterBlock[0].includes('linear-gradient'), 'hero stage should add a dedicated bottom fade so the stage resolves into the rows below')
assert.ok(stageAfterBlock[0].includes('height: 168px'), 'hero stage should carry a taller lower fade so the mood field reaches into the first shelves')
assert.ok(homeContentBlock[0].includes('padding: 0 0 14px'), 'home content shell should drop the left gutter so the hero can bleed fully into the stage area')
assert.ok(!heroStageBlock[0].includes('border:'), 'hero stage should stop feeling boxed in')
assert.ok(heroStageBlock[0].includes('height: clamp(580px, 46vw, 720px)'), 'hero stage should expand into a more dominant cinematic height inside the immersive shell')
assert.ok(heroStageBlock[0].includes('min-height: 580px'), 'hero stage should keep the taller immersive minimum footprint')
assert.ok(stageOverlayBlock[0].includes('rgba(5, 6, 9, 0.12) 0%'), 'hero stage overlay should preserve the top of the artwork instead of capping it with full opacity')
assert.ok(stageOverlayBlock[0].includes('rgba(8, 9, 11, 0.96) 100%'), 'hero stage overlay should still resolve the lower band firmly into the room')
assert.ok(homeStackBlock[0].includes('position: relative'), 'home shelf stack should anchor itself as part of the hero field instead of a detached page body')
assert.ok(homeStackBlock[0].includes('z-index: 2'), 'home shelf stack should sit above the hero fade when it overlaps the lower stage')
assert.ok(homeStackBlock[0].includes('margin-top: -20px'), 'home shelf stack should lightly climb into the hero fade without letting the hero copy collide with the first shelf')
assert.ok(homeTopbarBlock[0].includes('rgba(6, 7, 10, 0.56) 0%'), 'home topbar chrome should ease off the top-edge fade so frameless artwork can breathe')
assert.ok(immersiveHomeTopbarOverrideBlock[0].includes('backdrop-filter: none'), 'immersive home topbar should stop blurring the hero art now that frameless chrome owns the top edge')
assert.ok(css.includes(".gui2-shell[data-route='home'] .gui2-lang-button,\n.gui2-shell[data-route='home'] .gui2-user-chip {\n  border-color: rgba(255, 255, 255, 0.08);\n  background: rgba(8, 9, 11, 0.58);\n  backdrop-filter: none;"), 'home language and user chips should stop adding extra glass blur over the hero artwork')
assert.ok(!recentThumbBlock[0].includes('border:'), 'recent thumb should not render the odd white outline')
assert.ok(posterOverlayBlock[0].includes('linear-gradient'), 'poster cards should gain a richer in-art overlay instead of flat thumbnails')
assert.ok(posterChipBlock[0].includes('backdrop-filter'), 'poster cards should expose metadata as a polished in-art chip')
assert.ok(posterPopBlock[0].includes('opacity: 0'), 'poster cards should hide the action prompt until hover')
assert.ok(posterHitareaBlock[0].includes('transition:'), 'poster cards should expose a dedicated hitarea for stronger pop-out motion')
assert.ok(!recentRowBlock[0].includes('border-top'), 'recent rows should not render boxed separators around each anime')
assert.ok(recentRowBlock[0].includes('border: 0'), 'recent rows should explicitly remove the browser button outline')
assert.ok(loadingRecentRowBlock[0].includes('grid-template-columns: 118px minmax(0, 1fr)'), 'loading recent rows should keep the same layout footprint as the final content')
assert.ok(!navGroupSharedBlock[0].includes('position: sticky'), 'biblioteca group should not inherit sticky footer behavior')
assert.ok(!navGroupSharedBlock[0].includes('margin-top: auto'), 'biblioteca group should not inherit footer spacing behavior')
assert.ok(navFooterBlock[0].includes('margin-top: auto'), 'system footer should stay anchored at the bottom of the sidebar')
assert.ok(heroTransitionImageBlock[0].includes('opacity: 0.76'), 'hero transition should fade gently instead of blanking the whole stage')
assert.ok(routeSource.includes("const [homeMode, setHomeMode] = useState('anime')"), 'home route should default to anime mode and allow switching into manga mode')
assert.ok(routeSource.includes('const [recentIndex, setRecentIndex] = useState(0)'), 'home route should rotate recently updated items beside the hero')
assert.ok(routeSource.includes('const [laneSelections, setLaneSelections] = useState('), 'home route should keep independent category lane selections')
assert.ok(routeSource.includes('const heroTitleClassName = `gui2-homev2-hero-title'), 'hero route should classify long titles before rendering them')
assert.ok(routeSource.includes('const visibleRecentItems = useMemo(() => {'), 'home route should build a compact rotating window for the recent rail')
assert.ok(routeSource.includes('const heroBackdrop = hero?.banner || hero?.image || \'\''), 'hero route should explicitly separate backdrop selection from layout sizing')
assert.ok(routeSource.includes("const visibleSections = homeMode === 'manga' ? effectiveHomeData.mangaSections : effectiveHomeData.animeSections"), 'home route should drive shelves from the selected home mode while honoring the startup snapshot fallback')
assert.ok(routeSource.includes('const featuredRecentSection = effectiveHomeData.featuredRecentSection'), 'home route should read the dedicated recently-updated feature block from the effective first-paint data source')
assert.ok(routeSource.includes('const mangaFeaturedRecentSection = effectiveHomeData.mangaFeaturedRecentSection'), 'home route should read a dedicated manga recent rail payload from the effective first-paint data source')
assert.ok(routeSource.includes("const activeRecentSection = homeMode === 'manga' ? mangaFeaturedRecentSection : featuredRecentSection"), 'home route should switch the hero side rail payload by mode')
assert.ok(routeSource.includes('const deferredHomeReady = homeMangaGenreQuery.isFetched && (!recommendationSeedIDs.length || homeMangaRecommendationsQuery.isFetched)'), 'home route should treat deeper shelves as post-reveal hydration instead of required first-paint content')
assert.ok(routeSource.includes('const visibleAnimeLanes = deferredHomeReady ? animeLanes : animeLanes.slice(0, 3)'), 'home route should keep the opening anime reveal to a compact three-lane set')
assert.ok(routeSource.includes('const visibleMangaLanes = useMemo(() => {'), 'home route should compute a reduced opening manga lane set before deferred shelves arrive')
assert.ok(routeSource.includes('return (openingLanes.length > 0 ? openingLanes : mangaLanes).slice(0, 3)'), 'home route should surface a compact multi-lane manga opening set before deeper rows arrive')
assert.ok(routeSource.includes('gui2-homev2-mode-tabs'), 'home route should render explicit anime and manga mode tabs')
assert.ok(routeSource.includes('gui2-homev2-hero-switch'), 'home route should render the mode switch inside the hero')
assert.ok(routeSource.includes('gui2-homev2-stage-grid'), 'home route should rebuild the top row as one shared stage grid')
assert.ok(routeSource.includes('gui2-homev2-stage-main'), 'home route should compose the hero as a main stage column instead of an isolated card')
assert.ok(routeSource.includes('gui2-homev2-hero-body'), 'home route should keep title, button, and summary inside one editorial body')
assert.ok(routeSource.includes('gui2-homev2-hero-recent'), 'home route should render recently updated beside the hero again')
assert.ok(routeSource.includes('gui2-homev2-lane-tabs'), 'home route should render switchable category lanes')
assert.ok(routeSource.includes('chunkLaneItems(activeTab?.items || [], 7, 3)'), 'home lanes should move in overlapping three-card steps instead of blunt full-page swaps')
assert.ok(routeSource.includes('const finalStart = Math.max(items.length - pageSize, 0)'), 'home lanes should anchor the final page to a full-width window instead of ending on an underfilled trailing page')
assert.ok(routeSource.includes('pages.push(items.slice(finalStart, finalStart + pageSize))'), 'home lanes should add a final full window when the last three-step page would leave empty slots')
assert.ok(routeSource.includes('const [pageIndex, setPageIndex] = useState(0)'), 'home lanes should keep independent horizontal page state')
assert.ok(routeSource.includes('gui2-homev2-lane-arrow'), 'home lanes should render explicit horizontal paging controls')
assert.ok(routeSource.includes('gui2-homev2-lane-track'), 'home route should animate lane content between category selections')
assert.ok(routeSource.includes('const rotateMs = useMemo(() => getLaneRotateMs(lane.key, motionIndex), [lane.key, motionIndex])'), 'home lanes should compute independent autoplay pacing per row instead of sharing one timing value')
assert.ok(routeSource.includes('const initialDelayMs = useMemo(() => getLaneInitialDelayMs(lane.key, motionIndex), [lane.key, motionIndex])'), 'home lanes should start on staggered offsets so all shelves do not move in lockstep')
assert.ok(routeSource.includes('const timeoutId = window.setTimeout(() => {'), 'home lanes should delay autoplay startup to desynchronize row motion')
assert.ok(!routeSource.includes('Math.max(pageItems.length, 1)'), 'lane pages should not stretch short pages by deriving poster columns from the remaining item count')
assert.ok(!routeSource.includes("lane.actionLabel || 'View All'"), 'home lanes should drop the View All call-to-action to keep the rebuilt shelves cleaner')
assert.ok(!routeSource.includes('gui2-homev2-link'), 'home rows should not render View All links after the Home shelf rebuild')
assert.ok(routeSource.includes("buildLaneGenreTabs(laneItems, isEnglish)"), 'row genre filters should be derived from each shelf itself instead of reusing one global anime set')
assert.ok(!routeSource.includes('...animeGenreTabs'), 'featured shelves should stop inheriting the same global genre rows for every lane')
assert.ok(!routeSource.includes('gui2-homev2-mode-panel'), 'home route should not render boxed mode panels')
assert.ok(!routeSource.includes('gui2-homev2-spotlight'), 'home route should not render spotlight card panels')
assert.ok(!routeSource.includes('gui2-homev2-recent-grid'), 'home route should not push recently updated into a giant grid below the hero')
assert.ok(!routeSource.includes('hero.meta.join'), 'hero route should stop dumping the whole meta line into a stray text block')
assert.ok(routeSource.includes('className="gui2-homev2-poster-hitarea"'), 'home posters should render a dedicated hitarea so hover pop-outs can lift beyond the artwork bounds')
assert.ok(routeSource.includes("onOpenPoster={(item) => openMangaItem(item)}"), 'home shelves should open manga items differently once manga mode is active')
assert.ok(routeSource.includes("onOpenContinue={(_, item) => openAnimeItem(item)}"), 'continue watching cards should open the anime landing instead of routing to history')
assert.ok(routeSource.includes("const mangaContinueSection = mangaSectionMap['continue-reading-manga'] || null"), 'home route should keep a dedicated manga continue shelf separate from the manga lane stack')
assert.ok(routeSource.includes('const mangaFeaturedSections = useMemo('), 'home route should split manga personal shelves from deeper discovery rows')
assert.ok(routeSource.includes("title: isEnglish ? 'Recommended For You' : 'Recomendado para ti'"), 'manga route should expose the approved recommendation shelf copy')
assert.ok(routeSource.includes("title: isEnglish ? 'Fresh Manga Picks' : 'Manga fresco para descubrir'"), 'manga route should expose the approved fresh manga shelf copy')
assert.ok(routeSource.includes('visibleAnimeLanes.map((lane, index) => ('), 'home route should render the reduced opening anime lane set before deeper rows appear')
assert.ok(routeSource.includes('visibleMangaLanes.map((lane, index) => ('), 'home route should render the reduced opening manga lane set before deeper rows appear')
assert.ok(routeSource.includes('section.pageSize || 6'), 'continue watching should page titles in groups of six')
assert.ok(routeSource.includes('gui2-homev2-continue-track'), 'continue watching should render a sliding track for extra pages')
assert.ok(css.includes(".gui2-shell[data-shell-variant='immersive'] .gui2-topbar"), 'home should inherit the immersive shell instead of faking shell bleed alone')

console.log('home layout CSS tests passed')
