import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const cssPath = resolve(import.meta.dirname, '../../styles/gui2.css')
const routePath = resolve(import.meta.dirname, '../Gui2HomeRoute.jsx')
const css = readFileSync(cssPath, 'utf8')
const routeSource = readFileSync(routePath, 'utf8')

const posterRailBlock = css.match(/\.gui2-homev2-poster-rail\s*\{[^}]+\}/)
const continueRailBlock = css.match(/\.gui2-homev2-continue-rail\s*\{[^}]+\}/)
const continueViewportBlock = css.match(/\.gui2-homev2-continue-viewport\s*\{[^}]+\}/)
const continueTrackBlock = css.match(/\.gui2-homev2-continue-track\s*\{[^}]+\}/)
const recentThumbBlock = css.match(/\.gui2-homev2-recent-thumb\s*\{[^}]+\}/)
const recentRowBlock = css.match(/\.gui2-homev2-recent-row\s*\{[^}]+\}/)
const loadingRecentRowBlock = css.match(/\.gui2-homev2-loading-recent-row\s*\{[^}]+\}/)
const loadingPosterRailBlock = css.match(/\.gui2-homev2-loading-poster-rail\s*\{[^}]+\}/)
const navGroupSharedBlock = css.match(/\.gui2-nav-group,\s*\.gui2-nav-footer\s*\{[^}]+\}/)
const navFooterBlocks = [...css.matchAll(/^\s*\.gui2-nav-footer\s*\{[^}]+\}/gm)]
const navFooterBlock = navFooterBlocks.find((block) => block[0].includes('margin-top: auto'))
const heroTransitionImageBlock = css.match(/\.gui2-homev2-hero-stage\.transitioning \.gui2-homev2-hero-image,[^}]+\}/)

assert.ok(posterRailBlock, 'poster rail CSS block should exist')
assert.ok(continueRailBlock, 'continue rail CSS block should exist')
assert.ok(continueViewportBlock, 'continue viewport CSS block should exist')
assert.ok(continueTrackBlock, 'continue track CSS block should exist')
assert.ok(recentThumbBlock, 'recent thumb CSS block should exist')
assert.ok(recentRowBlock, 'recent row CSS block should exist')
assert.ok(loadingRecentRowBlock, 'loading recent row CSS block should exist')
assert.ok(loadingPosterRailBlock, 'loading poster rail CSS block should exist')
assert.ok(navGroupSharedBlock, 'shared nav group/footer CSS block should exist')
assert.ok(navFooterBlock, 'sidebar footer CSS block should exist')
assert.ok(heroTransitionImageBlock, 'hero transition CSS block should exist')
assert.ok(!posterRailBlock[0].includes('justify-content: space-between'), 'poster rail should not space cards apart')
assert.ok(!continueRailBlock[0].includes('justify-content: space-between'), 'continue rail should not space cards apart')
assert.ok(posterRailBlock[0].includes('justify-content: start'), 'poster rail should pack cards from the left')
assert.ok(continueRailBlock[0].includes('justify-content: start'), 'continue rail should pack cards from the left')
assert.ok(posterRailBlock[0].includes('1fr'), 'poster rail should stretch evenly across the desktop row')
assert.ok(continueRailBlock[0].includes('repeat(6, minmax(0, 1fr))'), 'continue rail should keep six desktop slots per page')
assert.ok(continueViewportBlock[0].includes('overflow: hidden'), 'continue viewport should clip the off-screen pages')
assert.ok(continueTrackBlock[0].includes('transition:'), 'continue track should animate page changes')
assert.ok(loadingPosterRailBlock[0].includes('repeat(6, minmax(0, 1fr))'), 'home loading shelves should mirror the six-column desktop rail rhythm')
assert.ok(!recentThumbBlock[0].includes('border:'), 'recent thumb should not render the odd white outline')
assert.ok(!recentRowBlock[0].includes('border-top'), 'recent rows should not render boxed separators around each anime')
assert.ok(recentRowBlock[0].includes('border: 0'), 'recent rows should explicitly remove the browser button outline')
assert.ok(loadingRecentRowBlock[0].includes('grid-template-columns: 118px minmax(0, 1fr)'), 'loading recent rows should keep the same layout footprint as the final content')
assert.ok(!navGroupSharedBlock[0].includes('position: sticky'), 'biblioteca group should not inherit sticky footer behavior')
assert.ok(!navGroupSharedBlock[0].includes('margin-top: auto'), 'biblioteca group should not inherit footer spacing behavior')
assert.ok(navFooterBlock[0].includes('margin-top: auto'), 'system footer should stay anchored at the bottom of the sidebar')
assert.ok(heroTransitionImageBlock[0].includes('opacity: 0.76'), 'hero transition should fade gently instead of blanking the whole stage')
assert.ok(routeSource.includes("onOpenContinue={(_, item) => openAnimeItem(item)}"), 'continue watching cards should open the anime landing instead of routing to history')
assert.ok(routeSource.includes('section.pageSize || 6'), 'continue watching should page titles in groups of six')
assert.ok(routeSource.includes('gui2-homev2-continue-track'), 'continue watching should render a sliding track for extra pages')

console.log('home layout CSS tests passed')
