import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const routePath = resolve(import.meta.dirname, './Gui2MyListsRoute.jsx')
const cssPath = resolve(import.meta.dirname, '../styles/gui2.css')
const routeSource = readFileSync(routePath, 'utf8')
const css = readFileSync(cssPath, 'utf8')

assert.ok(routeSource.includes('gui2-lists-hero gui2-lists-hero-premium'), 'My Lists should use the premium ownership hero treatment')
assert.ok(routeSource.includes('gui2-mylist-switchline gui2-lists-hero gui2-lists-hero-premium gui2-motion-enter'), 'My Lists should reduce the top area to a quiet anime/manga switchline')
assert.ok(routeSource.includes('gui2-mylist-grid-shell gui2-lists-shelf gui2-motion-enter'), 'My Lists should animate the cover-driven collection shell as the main surface')
assert.ok(routeSource.includes('gui2-mylist-card'), 'My Lists should render cover-driven cards instead of relying on the old table rows')
assert.ok(routeSource.includes('Saved locally for now'), 'My Lists should explain that AniList tracking changes stay local during fallback')
assert.ok(routeSource.includes('gui2-mylist-card-edit'), 'My Lists cards should expose a dedicated edit action')
assert.ok(routeSource.includes('gui2-mylist-status-shelf'), 'My Lists should group the All view into status shelves')
assert.ok(routeSource.includes('gui2-mylist-status-shelf-grid'), 'My Lists status shelves should render their own card grids')
assert.ok(routeSource.includes('gui2-mylist-editor-backdrop'), 'My Lists should render a backdrop so users can dismiss the editor by returning to the library')
assert.ok(routeSource.includes('groupedEntries={groupedEntries}'), 'My Lists should pass grouped status shelves into the cover-driven surface')
assert.ok(routeSource.includes('gui2-mylist-sort-wrap'), 'My Lists should expose a sort control beside search')
assert.ok(routeSource.includes('gui2-mylist-sort-menu'), 'My Lists should render the sort dropdown menu')
assert.ok(routeSource.includes('currentDateInput()'), 'My Lists should fall back to the current day for new start dates when no real synced date exists')
assert.ok(routeSource.includes('entry?.started_at'), 'My Lists should prefer started dates coming from synced entry data before using local fallbacks')
assert.ok(routeSource.includes('useQueryClient'), 'My Lists should read boot-warmed list payloads through the shared query client')
assert.ok(routeSource.includes("queryClient.getQueryData(['gui2-my-lists-anime-entries'])"), 'My Lists should bootstrap anime entries from the startup cache before issuing route-local loads')
assert.ok(routeSource.includes("queryClient.getQueryData(['gui2-my-lists-manga-entries'])"), 'My Lists should bootstrap manga entries from the startup cache before issuing route-local loads')
assert.ok(routeSource.includes('createPortal('), 'My Lists editor should render as a true overlay sheet instead of staying attached to the page layout')
assert.ok(routeSource.includes('document.body.style.overflow = \'hidden\''), 'My Lists should lock background scroll while the edit overlay is open')
assert.ok(!routeSource.includes('<h1 className="gui2-mylist-title">'), 'My Lists should not render a redundant page title header')
assert.ok(!routeSource.includes('Edit Entry'), 'My Lists cards should use an icon edit affordance instead of a text button')
assert.ok(!routeSource.includes('Editar entrada'), 'My Lists cards should use an icon edit affordance instead of a text button')
assert.ok(!routeSource.includes('gui2-mylist-card-subtitle'), 'My Lists cards should prioritize a single title line system for consistent heights')
assert.ok(routeSource.includes('Completed On'), 'My Lists should expose a completion date field in the editor')
assert.ok(!routeSource.includes('Notes'), 'My Lists editor should not keep a local-only notes field')
assert.ok(!routeSource.includes('Notas'), 'My Lists editor should not keep a local-only notes field')
assert.ok(!routeSource.includes('Etiquetas'), 'My Lists editor should not keep a local-only tags field')
assert.ok(css.includes('.gui2-lists-hero-premium {'), 'premium My Lists hero CSS should exist')
assert.ok(css.includes('.gui2-lists-shelf {'), 'My Lists shelf CSS should exist')
assert.ok(css.includes('.gui2-lists-shell-premium {'), 'My Lists shell premium CSS should exist')
assert.ok(css.includes('.gui2-mylist-grid-shell {'), 'My Lists cover-driven grid shell CSS should exist')
assert.ok(css.includes('.gui2-mylist-card:hover {'), 'My Lists cards should define a stronger hover state')
assert.ok(css.includes('.gui2-mylist-editor-drawer {'), 'My Lists should define the on-demand editor drawer surface')
assert.ok(css.includes('.gui2-mylist-status-shelf {'), 'My Lists should style grouped status shelves')
assert.ok(css.includes('.gui2-mylist-editor-backdrop {'), 'My Lists should style the editor backdrop dismissal layer')
assert.ok(css.includes('.gui2-mylist-card-edit-icon {'), 'My Lists should style the icon-only card edit affordance')
assert.ok(css.includes('.gui2-mylist-sort-wrap {'), 'My Lists should style the sort control container')
assert.ok(css.includes('.gui2-mylist-sort-menu {'), 'My Lists should style the sort dropdown menu')
assert.ok(css.includes('.gui2-mylist-editor-image-backdrop {'), 'My Lists editor should use a layered image backdrop to avoid dead space around tall covers')
assert.ok(css.includes('margin-left: auto;'), 'My Lists should keep the actions menu pushed away from search and sort so the filter dropdown sits beside search')
assert.ok(css.includes('background: rgba(5, 6, 9, 0.42);'), 'My Lists overlay should dim the library behind the editor sheet')
assert.ok(css.includes('position: fixed;'), 'My Lists editor drawer should stay visible as an overlay sheet while the library scrolls')
assert.ok(css.includes('pointer-events: auto;'), 'My Lists edit affordance should remain clickable so edit interactions do not fall through to the landing-page card action')
assert.ok(css.includes('.gui2-mylist-grid-shell {\n  position: relative;'), 'My Lists should keep a dedicated embedded grid shell block')
assert.ok(css.includes('background: linear-gradient(180deg, rgba(15, 17, 20, 0.34), rgba(9, 11, 14, 0));'), 'My Lists grid shell should feel embedded into the room instead of floating without atmosphere')
assert.ok(css.includes('.gui2-mylist-card-art {\n  position: relative;'), 'My Lists should keep a dedicated card-art surface block')
assert.ok(css.includes('border: 1px solid rgba(255, 255, 255, 0.04);'), 'My Lists card art should use a softer frame so the collection feels curated rather than tool-heavy')

console.log('gui2 my lists layout tests passed')
