import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const cssPath = resolve(import.meta.dirname, '../../styles/gui2.css')
const localPagePath = resolve(import.meta.dirname, '../../../pages/Local.jsx')
const animeRoutePath = resolve(import.meta.dirname, '../Gui2AnimeDetailRoute.jsx')
const mangaRoutePath = resolve(import.meta.dirname, '../Gui2MangaDetailRoute.jsx')

const css = readFileSync(cssPath, 'utf8')
const localPage = readFileSync(localPagePath, 'utf8')
const animeRoute = readFileSync(animeRoutePath, 'utf8')
const mangaRoute = readFileSync(mangaRoutePath, 'utf8')

assert.ok(!localPage.includes("navigate('/sources')"), 'local library should not expose the hidden sources shortcut in the header action row')
assert.ok(!localPage.includes("navigate('/settings')"), 'local library should not expose a dedicated settings action in the stripped-down hero')
assert.ok(!localPage.includes('<section className="gui2-localv2-overview">'), 'local library should remove the old overview stats band')
assert.ok(!localPage.includes('className="gui2-localv2-controls"'), 'local library should remove the old sort, filter, and view-mode controls')
assert.ok(!localPage.includes('className="gui2-localv2-view-toggle"'), 'local library should remove the grid/list toggle from the redesigned surface')
assert.ok(!localPage.includes('<LocalSelectionPanel'), 'local library should not render the persistent right-side inspector')
assert.ok(!localPage.includes('className="gui2-localv2-activity"'), 'local library should remove the recent activity rail')
assert.ok(!localPage.includes('className="gui2-localv2-footer"'), 'local library should remove the footer status strip')
assert.ok(localPage.includes('className="gui2-localv2-grid"'), 'local library should keep a poster-grid-first content stage')
assert.ok(localPage.includes('Scan Folder'), 'local library should preserve the scan-folder action')
assert.ok(localPage.includes('Add Folder'), 'local library should preserve the add-folder action')
assert.ok(!css.includes('.gui2-localv2-overview {'), 'local CSS should no longer style the removed overview band')
assert.ok(!css.includes('.gui2-localv2-content {'), 'local CSS should no longer style the removed three-column content layout')
assert.ok(!css.includes('.gui2-localv2-panel {'), 'local CSS should no longer style the removed inspector panel')
assert.ok(!css.includes('.gui2-localv2-activity {'), 'local CSS should no longer style the removed activity rail')
assert.ok(!css.includes('.gui2-localv2-footer {'), 'local CSS should no longer style the removed footer strip')

assert.ok(animeRoute.includes('gui2-landing-page gui2-landing-page--anime'), 'local anime route should use the landing-page system')
assert.ok(mangaRoute.includes('gui2-landing-page gui2-landing-page--manga'), 'local manga route should use the landing-page system')
assert.ok(!animeRoute.includes('gui2-detail-page'), 'local anime route should not use the old gui2 detail page shell')
assert.ok(!mangaRoute.includes('gui2-detail-page'), 'local manga route should not use the old gui2 detail page shell')
assert.ok(!animeRoute.includes('Local anime landing'), 'local anime route should not inject the old local landing eyebrow copy')
assert.ok(!mangaRoute.includes('Local manga landing'), 'local manga route should not inject the old local landing eyebrow copy')
assert.ok(!animeRoute.includes('<aside className="gui2-landing-sidecard">'), 'local anime landing hero should not render a duplicate Details sidecard above the workspace')
assert.ok(!mangaRoute.includes('<aside className="gui2-landing-sidecard">'), 'local manga landing hero should not render a duplicate Details sidecard above the workspace')
assert.ok(animeRoute.includes('<LandingMetaPanel title={isEnglish ? \'Details\' : \'Detalles\'} rows={detailRows} />'), 'local anime landing should keep the lower Details panel in the aside')
assert.ok(mangaRoute.includes('<LandingMetaPanel title={isEnglish ? \'Details\' : \'Detalles\'} rows={detailRows} />'), 'local manga landing should keep the lower Details panel in the aside')
assert.ok(animeRoute.includes('className="gui2-landing-panel gui2-landing-panel--progression"'), 'local anime landing should mark the episode queue as a progression surface')
assert.ok(mangaRoute.includes('className="gui2-landing-panel gui2-landing-panel--progression"'), 'local manga landing should mark the chapter queue as a progression surface')
assert.ok(animeRoute.includes('buildEpisodeGroups'), 'local anime route should preserve subfolder grouping')
assert.ok(animeRoute.includes('folder_name'), 'local anime route should still read folder_name from episode payloads')

console.log('local layout tests passed')
