import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = readFileSync(resolve(import.meta.dirname, './NipahBootRoot.jsx'), 'utf8')
const indexHtml = readFileSync(resolve(import.meta.dirname, '../../../index.html'), 'utf8')

assert.ok(source.includes('const [appMounted, setAppMounted] = useState(false)'), 'boot root should keep the app shell unmounted during warm startup')
assert.ok(source.includes('setAppMounted(true)'), 'boot root should only mount the app after warm launch completes')
assert.ok(source.includes('{appMounted ? children : null}'), 'boot root should not render the shell behind the boot window')
assert.ok(source.includes('loadStartupSnapshot()'), 'boot root should consult the persisted startup snapshot before waiting on a full live warmup')
assert.ok(source.includes('isStartupSnapshotUsable('), 'boot root should validate persisted startup snapshots against the current launch context')
assert.ok(source.includes("queryClient.setQueryData(['gui2-home-startup-snapshot'"), 'boot root should seed the startup snapshot cache from persisted storage before the shell mounts')
assert.ok(source.includes("queryClient.setQueryData(['gui2-home-startup-readiness'"), 'boot root should seed startup readiness from persisted storage before the shell mounts')
assert.ok(source.includes("import {"), 'boot root should import the shared boot stage model')
assert.ok(source.includes('BOOT_CATCHPHRASE'), 'boot root should render the approved catchphrase from shared boot state')
assert.ok(source.includes('gui2-boot-scene'), 'boot root should render a full authored scene around the startup chamber')
assert.ok(source.includes('gui2-boot-scene-lamp'), 'boot root should render the warm left lamp cue that fills the frameless window perimeter')
assert.ok(source.includes('gui2-boot-scene-desk'), 'boot root should render a grounding desk plane so the chamber does not float in dead space')
assert.ok(source.includes('gui2-boot-room'), 'boot root should render a warm room wrapper around the startup chamber')
assert.ok(source.includes('gui2-boot-chamber'), 'boot root should render a dedicated cozy chamber instead of the old grid stage')
assert.ok(source.includes('gui2-boot-illustration'), 'boot root should render the sleepy chibi illustration inside the chamber')
assert.ok(source.includes('nipah-boot-cozy-host-transparent.png'), 'boot root should render the transparent production chibi asset')
assert.ok(source.includes('setting the room for tonight') || source.includes('BOOT_CATCHPHRASE'), 'boot root should render the approved world-opening catchphrase')
assert.ok(source.includes('gui2-boot-status-track'), 'boot root should expose a real loading track instead of static status decoration')
assert.ok(!source.includes('gui2-boot-status-label'), 'boot root should not render status copy once the loading indicator is reduced to the wandering drop only')
assert.ok(!source.includes('gui2-boot-status-mark'), 'boot root should not render rail marks once the loading indicator is reduced to the wandering drop only')
assert.ok(source.includes("document.getElementById('boot-fallback')?.remove()"), 'boot root should remove the pre-react fallback once the real boot overlay mounts')
assert.ok(!source.includes('window.requestAnimationFrame(() => {\r\n          Promise.resolve(wails.completeStartupLaunch?.()).catch(() => {})'), 'boot root should not re-trigger startup launch after the shell is already mounted')
assert.ok(indexHtml.includes('/nipah-boot-cozy-host-transparent.png'), 'fallback boot should use the same transparent production chibi asset as the live overlay')
assert.ok(indexHtml.includes('boot-fallback-scene-lamp'), 'fallback boot should include the same left lamp cue as the live overlay')
assert.ok(indexHtml.includes('boot-fallback-status-track'), 'fallback boot should include a real loading track instead of a copy-only state')
assert.ok(!indexHtml.includes('boot-fallback-status-label'), 'fallback boot should not render loading copy once the indicator is reduced to the wandering drop only')
assert.ok(!indexHtml.includes('boot-fallback-status-mark'), 'fallback boot should not render rail marks once the indicator is reduced to the wandering drop only')

console.log('boot root tests passed')
