import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const cssPath = resolve(import.meta.dirname, '../../styles/gui2.css')
const searchPath = resolve(import.meta.dirname, '../../../pages/Search.jsx')
const mangaPath = resolve(import.meta.dirname, '../../../pages/MangaSearch.jsx')
const surfacePath = resolve(import.meta.dirname, './Gui2OnlineCatalogSurface.jsx')
const catalogBackendPath = resolve(import.meta.dirname, '../../../../../backend/metadata/catalog_requests.go')

const css = readFileSync(cssPath, 'utf8')
const searchSource = readFileSync(searchPath, 'utf8')
const mangaSource = readFileSync(mangaPath, 'utf8')
const surfaceSource = readFileSync(surfacePath, 'utf8')
const catalogBackendSource = readFileSync(catalogBackendPath, 'utf8')

const selectBlock = css.match(/\.gui2-catalog-select\s*\{[^}]+\}/)
const dropdownBlock = css.match(/\.gui2-catalog-select \.custom-select-dropdown\s*\{[^}]+\}/)
const overlayBlock = css.match(/\.gui2-catalog-card-overlay\s*\{[^}]+\}/)
const gridBlock = css.match(/\.gui2-catalog-grid\s*\{[^}]+\}/)
const gridItemBlock = css.match(/\.gui2-catalog-grid-item\s*\{[^}]+\}/)
const bodyBlock = css.match(/\.gui2-catalog-card-body\s*\{[^}]+\}/)
const multiSelectBlock = css.match(/\.gui2-catalog-multi-select\s*\{[^}]+\}/)
const multiValueBlock = css.match(/\.gui2-catalog-multi-value\s*\{[^}]+\}/)

assert.ok(selectBlock, 'catalog select CSS block should exist')
assert.ok(dropdownBlock, 'catalog dropdown CSS block should exist')
assert.ok(overlayBlock, 'catalog overlay CSS block should exist')
assert.ok(gridBlock, 'catalog grid CSS block should exist')
assert.ok(gridItemBlock, 'catalog grid item CSS block should exist')
assert.ok(bodyBlock, 'catalog card body CSS block should exist')
assert.ok(multiSelectBlock, 'catalog multi-select CSS block should exist')
assert.ok(multiValueBlock, 'catalog multi-value CSS block should exist')

assert.ok(selectBlock[0].includes('position: relative'), 'catalog select should anchor floating dropdowns')
assert.ok(dropdownBlock[0].includes('position: absolute'), 'catalog dropdown should float instead of pushing the filter bar')
assert.ok(dropdownBlock[0].includes('z-index: 50'), 'catalog dropdown should sit above the catalog surface')
assert.ok(overlayBlock[0].includes('display: none'), 'catalog overlay should be disabled so no dark square hides titles')
assert.ok(gridBlock[0].includes('minmax(158px, 1fr)'), 'catalog grid should use a denser fixed card lane on desktop')
assert.ok(gridItemBlock[0].includes('display: flex'), 'catalog grid items should stretch cards to consistent heights')
assert.ok(bodyBlock[0].includes('min-height: 78px'), 'catalog card body should reserve a consistent title/meta area')
assert.ok(multiSelectBlock[0].includes('position: relative'), 'catalog multi-select should anchor the stacked genre dropdown')
assert.ok(searchSource.includes('const CATALOG_PAGE_SIZE = 48'), 'anime catalog should default to 48 items per page')
assert.ok(mangaSource.includes('const CATALOG_PAGE_SIZE = 48'), 'manga catalog should default to 48 items per page')
assert.ok(searchSource.includes("queryKey: ['anime-catalog', appLang, catalogSort, catalogGenres.join(''), catalogSeason, catalogYear, catalogPage, catalogFormat, catalogStatus]".replace("join('')","join(',')")), 'anime catalog query key should react to format and status changes')
assert.ok(mangaSource.includes("queryKey: ['manga-catalog', lang, catalogSort, catalogGenres.join(''), catalogYear, catalogPage, catalogFormat, catalogStatus]".replace("join('')","join(',')")), 'manga catalog query key should react to format and status changes')
assert.ok(!searchSource.includes('Promise.race(['), 'anime catalog should not bail out early into the 20-item fallback on a slow first page')
assert.ok(!mangaSource.includes('Promise.race(['), 'manga catalog should not bail out early into a fallback shelf on a slow first page')
assert.ok(catalogBackendSource.includes('const aniListCatalogPerPage = 48'), 'catalog backend should keep the 48-item page size contract')
assert.ok(!searchSource.includes('gui2-catalog-card-overlay'), 'anime cards should not render the disabled overlay element')
assert.ok(!mangaSource.includes('gui2-catalog-card-overlay'), 'manga cards should not render the disabled overlay element')
assert.ok(searchSource.includes('gui2-catalog-multi-select'), 'anime catalog should render the shared multi-select genre control')
assert.ok(mangaSource.includes('gui2-catalog-multi-select'), 'manga catalog should render the shared multi-select genre control')
assert.ok(!searchSource.includes('GENRES.slice(0, 8)'), 'anime catalog should expose the full genre list instead of eight hard-coded chips')
assert.ok(!mangaSource.includes('GENRES.slice(0, 8)'), 'manga catalog should expose the full genre list instead of eight hard-coded chips')
assert.ok(surfaceSource.includes('onJumpToPage'), 'catalog pagination should support clicking specific page chips')
assert.ok(surfaceSource.includes('type="button"'), 'catalog page chips should render as interactive buttons')
assert.ok(surfaceSource.includes('buildCatalogPageChips'), 'catalog pagination should use a shared three-chip builder')
assert.ok(surfaceSource.includes('return [1, 2, 3]'), 'catalog pagination should offer three upfront page options from page one')
assert.ok(surfaceSource.includes('gui2-catalog-footer-ellipsis'), 'catalog pagination should render a non-clickable ellipsis marker')

console.log('catalog layout tests passed')
