import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const cssPath = resolve(import.meta.dirname, '../../styles/gui2.css')
const searchPath = resolve(import.meta.dirname, '../../../pages/Search.jsx')
const mangaPath = resolve(import.meta.dirname, '../../../pages/MangaSearch.jsx')
const surfacePath = resolve(import.meta.dirname, './Gui2OnlineCatalogSurface.jsx')
const catalogBackendPath = resolve(import.meta.dirname, '../../../../../backend/metadata/catalog_requests.go')

const css = readFileSync(cssPath, 'utf8')
const searchSource = readFileSync(searchPath, 'utf8')
const mangaSource = readFileSync(mangaPath, 'utf8')
const surfaceSource = readFileSync(surfacePath, 'utf8')
const catalogBackendSource = readFileSync(catalogBackendPath, 'utf8')

const selectBlock = css.match(/\.gui2-catalog-select\s*\{[^}]+\}/)
const dropdownBlock = css.match(/\.gui2-catalog-select \.custom-select-dropdown\s*\{[^}]+\}/)
const overlayBlock = css.match(/\.gui2-catalog-card-overlay\s*\{[^}]+\}/)
const gridBlock = css.match(/\.gui2-catalog-grid\s*\{[^}]+\}/)
const gridItemBlock = css.match(/\.gui2-catalog-grid-item\s*\{[^}]+\}/)
const bodyBlock = css.match(/\.gui2-catalog-card-body\s*\{[^}]+\}/)
const multiSelectBlock = css.match(/\.gui2-catalog-multi-select\s*\{[^}]+\}/)
const multiValueBlock = css.match(/\.gui2-catalog-multi-value\s*\{[^}]+\}/)
const shellPremiumBlock = css.match(/\.gui2-catalog-shell-premium\s*\{[^}]+\}/)
const filterCellBlock = css.match(/\.gui2-catalog-filter-cell\s*\{[^}]+\}/)
const resultsShellPremiumBlock = css.match(/\.gui2-catalog-results-shell-premium\s*\{[^}]+\}/)
const headerMinimalBlock = css.match(/\.gui2-catalog-header-minimal\s*\{[^}]+\}/)
const utilitiesBlock = css.match(/\.gui2-catalog-utilities\s*\{[^}]+\}/)
const utilitiesSearchBlock = css.match(/\.gui2-catalog-utilities-search\s*\{[^}]+\}/)
const filterbarPillsBlock = css.match(/\.gui2-catalog-filterbar-pills\s*\{[^}]+\}/)
const filterLabelRowBlock = css.match(/\.gui2-catalog-filter-labelrow\s*\{[^}]+\}/)

assert.ok(selectBlock, 'catalog select CSS block should exist')
assert.ok(dropdownBlock, 'catalog dropdown CSS block should exist')
assert.ok(overlayBlock, 'catalog overlay CSS block should exist')
assert.ok(gridBlock, 'catalog grid CSS block should exist')
assert.ok(gridItemBlock, 'catalog grid item CSS block should exist')
assert.ok(bodyBlock, 'catalog card body CSS block should exist')
assert.ok(multiSelectBlock, 'catalog multi-select CSS block should exist')
assert.ok(multiValueBlock, 'catalog multi-value CSS block should exist')
assert.ok(shellPremiumBlock, 'catalog shell premium CSS block should exist')
assert.ok(filterCellBlock, 'catalog filter cell CSS block should exist')
assert.ok(resultsShellPremiumBlock, 'catalog results shell premium CSS block should exist')
assert.ok(headerMinimalBlock, 'catalog minimal header CSS block should exist')
assert.ok(utilitiesBlock, 'catalog utilities CSS block should exist')
assert.ok(utilitiesSearchBlock, 'catalog utilities search CSS block should exist')
assert.ok(filterbarPillsBlock, 'catalog pill filter bar CSS block should exist')
assert.ok(filterLabelRowBlock, 'catalog filter label row CSS block should exist')

assert.ok(selectBlock[0].includes('position: relative'), 'catalog select should anchor floating dropdowns')
assert.ok(dropdownBlock[0].includes('position: absolute'), 'catalog dropdown should float instead of pushing the filter bar')
assert.ok(dropdownBlock[0].includes('z-index: 50'), 'catalog dropdown should sit above the catalog surface')
assert.ok(overlayBlock[0].includes('display: none'), 'catalog overlay should be disabled so no dark square hides titles')
assert.ok(gridBlock[0].includes('minmax(var(--gui2-catalog-card-min), 1fr)'), 'catalog grid should size cards through the shared room token so anime and manga can vary tone without forking the grid')
assert.ok(gridItemBlock[0].includes('display: flex'), 'catalog grid items should stretch cards to consistent heights')
assert.ok(bodyBlock[0].includes('min-height: 84px'), 'catalog card body should reserve a larger title/meta area for the more dominant poster cards')
assert.ok(multiSelectBlock[0].includes('position: relative'), 'catalog multi-select should anchor the stacked genre dropdown')
assert.ok(shellPremiumBlock[0].includes('gap: 22px'), 'catalog shell premium should open more breathing room between the quiet room sections')
assert.ok(filterCellBlock[0].includes('background: transparent;'), 'catalog filter cells should stop behaving like stacked boxes')
assert.ok(filterCellBlock[0].includes('box-shadow: none;'), 'catalog filter cells should remove stacked shell depth in favor of lighter pills')
assert.ok(resultsShellPremiumBlock[0].includes('border-top:'), 'catalog results shell premium should rejoin the poster field to the room with a softer divider')
assert.ok(headerMinimalBlock[0].includes('justify-items: start;'), 'catalog title band should be reduced to a simple title-only anchor')
assert.ok(utilitiesBlock[0].includes('justify-items: center;'), 'catalog utilities should center the real controls above the poster field')
assert.ok(utilitiesBlock[0].includes('gap: 16px;'), 'catalog utilities should leave more breathing room between search and tool controls')
assert.ok(utilitiesBlock[0].includes('margin-top: -'), 'catalog utilities should use the frameless top space more aggressively')
assert.ok(utilitiesSearchBlock[0].includes('width: min(100%, 780px);'), 'catalog search should anchor the centered utilities band without spanning like a boxed header strip')
assert.ok(filterbarPillsBlock[0].includes('grid-template-columns: repeat(auto-fit, minmax(150px, max-content));'), 'catalog filters should return to a horizontal pill-led organization')
assert.ok(filterLabelRowBlock[0].includes('display: inline-flex;'), 'catalog should present calmer utility labels so each tool reads clearly')
assert.ok(searchSource.includes('const CATALOG_PAGE_SIZE = 36'), 'anime catalog should reduce per-page density to support more dominant cards')
assert.ok(mangaSource.includes('const CATALOG_PAGE_SIZE = 36'), 'manga catalog should reduce per-page density to support more dominant cards')
assert.ok(searchSource.includes("queryKey: ['anime-catalog', appLang, catalogSort, catalogGenres.join(''), catalogSeason, catalogYear, catalogPage, catalogFormat, catalogStatus]".replace("join('')","join(',')")), 'anime catalog query key should react to format and status changes')
assert.ok(mangaSource.includes("queryKey: ['manga-catalog', lang, catalogSort, catalogGenres.join(''), catalogYear, catalogPage, catalogFormat, catalogStatus]".replace("join('')","join(',')")), 'manga catalog query key should react to format and status changes')
assert.ok(!searchSource.includes('Promise.race(['), 'anime catalog should not bail out early into the 20-item fallback on a slow first page')
assert.ok(!mangaSource.includes('Promise.race(['), 'manga catalog should not bail out early into a fallback shelf on a slow first page')
assert.ok(catalogBackendSource.includes('const aniListCatalogPerPage = 36'), 'catalog backend should reduce per-page density to match the larger-card contract')
assert.ok(!searchSource.includes('gui2-catalog-card-overlay'), 'anime cards should not render the disabled overlay element')
assert.ok(!mangaSource.includes('gui2-catalog-card-overlay'), 'manga cards should not render the disabled overlay element')
assert.ok(searchSource.includes('gui2-catalog-multi-select'), 'anime catalog should render the shared multi-select genre control')
assert.ok(mangaSource.includes('gui2-catalog-multi-select'), 'manga catalog should render the shared multi-select genre control')
assert.ok(!searchSource.includes('GENRES.slice(0, 8)'), 'anime catalog should expose the full genre list instead of eight hard-coded chips')
assert.ok(!mangaSource.includes('GENRES.slice(0, 8)'), 'manga catalog should expose the full genre list instead of eight hard-coded chips')
assert.ok(surfaceSource.includes('onJumpToPage'), 'catalog pagination should support clicking specific page chips')
assert.ok(surfaceSource.includes('type="button"'), 'catalog page chips should render as interactive buttons')
assert.ok(surfaceSource.includes('buildCatalogPageChips'), 'catalog pagination should use a shared three-chip builder')
assert.ok(surfaceSource.includes('return [1, 2, 3]'), 'catalog pagination should offer three upfront page options from page one')
assert.ok(surfaceSource.includes('gui2-catalog-footer-ellipsis'), 'catalog pagination should render a non-clickable ellipsis marker')
assert.ok(surfaceSource.includes('gui2-catalog-shell gui2-catalog-shell-premium'), 'catalog surface should opt into the premium embedded room shell')
assert.ok(surfaceSource.includes('mode = \'anime\''), 'catalog surface should support an anime-first room mode by default')
assert.ok(surfaceSource.includes('gui2-catalog-header gui2-catalog-header-minimal'), 'catalog surface should reduce the top band to a title-only header')
assert.ok(surfaceSource.includes('gui2-catalog-utilities'), 'catalog surface should render a centered utilities field above the poster grid')
assert.ok(surfaceSource.includes('gui2-catalog-utilities-search'), 'catalog surface should keep search inside the centered utilities field')
assert.ok(surfaceSource.includes('gui2-catalog-filterbar gui2-catalog-filterbar-quiet gui2-catalog-filterbar-pills'), 'catalog filter bar should return to a horizontal pill-led structure')
assert.ok(surfaceSource.includes('gui2-catalog-results-shell gui2-catalog-results-shell-premium'), 'catalog results shell should opt into the embedded premium surface')
assert.ok(!surfaceSource.includes('gui2-catalog-toolbar-pill'), 'catalog surface should remove the noisy source/result/page utility pills completely')
assert.ok(css.includes('.gui2-catalog-source-option-tags'), 'catalog CSS should support inline source taxonomy tags for tuned source selection')
assert.ok(searchSource.includes('mode="anime"'), 'Anime Online should opt into the anime discovery-room mode')
assert.ok(mangaSource.includes('mode="manga"'), 'Manga Online should opt into the manga discovery-room mode')
assert.ok(!searchSource.includes('summaryPills={searchSummaryPills}'), 'Anime Online should remove the extra summary utility pills')
assert.ok(!mangaSource.includes('summaryPills={mangaSummaryPills}'), 'Manga Online should remove the extra summary utility pills')
assert.ok(!searchSource.includes('{subtitle ? <p className="online-section-copy">{subtitle}</p> : null}'), 'Anime Online should remove the extra section helper copy under result headers')
assert.ok(!mangaSource.includes('{subtitle ? <p className="online-section-copy">{subtitle}</p> : null}'), 'Manga Online should remove the extra section helper copy under result headers')
assert.ok(searchSource.includes("language: 'Spanish'"), 'Anime Online source metadata should classify Spanish-language sources')
assert.ok(searchSource.includes("language: 'English'"), 'Anime Online source metadata should classify English-language sources')
assert.ok(searchSource.includes("audio: 'Sub | Dub'"), 'Anime Online source metadata should classify sources with dub availability')
assert.ok(searchSource.includes('gui2-catalog-source-option-tags'), 'Anime Online source picker should render quiet taxonomy tags instead of another summary bar')
assert.ok(searchSource.includes('ANIME_SOURCE_LANGUAGE_OPTIONS'), 'Anime Online should separate source language from source selection explicitly')
assert.ok(searchSource.includes('value={activeSourceLanguage}'), 'Anime Online source utilities should expose a dedicated language selector')
assert.ok(searchSource.includes('options={filteredAnimeSourceOptions}'), 'Anime Online source utilities should filter source choices by the selected language')
assert.ok(!searchSource.includes('gui2-catalog-query-btn'), 'Anime Online should remove the redundant search button from the search bar')
assert.ok(!mangaSource.includes('gui2-catalog-query-btn'), 'Manga Online should remove the redundant search button from the search bar')
assert.ok(searchSource.includes('description=""'), 'Anime Online should strip the boxed top banner down to title only')
assert.ok(mangaSource.includes('description=""'), 'Manga Online should strip the boxed top banner down to title only')

console.log('catalog layout tests passed')
