import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const detailPath = resolve(import.meta.dirname, './OnlineMangaDetail.jsx')
const cssPath = resolve(import.meta.dirname, '../../gui-v2/styles/gui2.css')
const detailSource = readFileSync(detailPath, 'utf8')
const css = readFileSync(cssPath, 'utf8')

const landingDetailsSidecardStart = detailSource.indexOf('<aside className="gui2-landing-sidecard">')
const landingDetailsPanelStart = detailSource.indexOf('<LandingMetaPanel title={isEnglish ? \'Details\' : \'Detalles\'} rows={detailRows} />')
const editorialChapterTableStart = detailSource.indexOf('className="gui2-landing-chapter-table gui2-manga-landing-chapters-editorial"')
const landingProgressionPanelStart = detailSource.indexOf('className="gui2-landing-panel gui2-landing-panel--progression"')
const landingPaginationStart = detailSource.indexOf('className="gui2-landing-queue-pagination gui2-landing-queue-pagination--editorial"')
const landingRecommendationsStart = detailSource.indexOf('<LandingRecommendationsStage')
const mangaLandingHeroBlock = css.match(/^\s*\.gui2-landing-page--manga \.gui2-landing-hero\s*\{[^}]+\}/m)
const landingWorkspaceBlock = css.match(/^\s*\.gui2-landing-workspace\s*\{[^}]+\}/m)
const landingPanelBlock = css.match(/^\s*\.gui2-landing-sidecard,\s*[\r\n]+\s*\.gui2-landing-panel\s*\{[^}]+\}/m)
const immersiveLandingTopbarBlock = css.match(/^\s*\.gui2-shell\[data-shell-variant='immersive'\]\[data-route='anime-detail'\] \.gui2-topbar,\s*[\r\n]+\s*\.gui2-shell\[data-shell-variant='immersive'\]\[data-route='manga-detail'\] \.gui2-topbar\s*\{[^}]+\}/m)

assert.equal(landingDetailsSidecardStart, -1, 'gui-v2 manga landing hero should not render a duplicate Details sidecard above the chapter list')
assert.ok(landingDetailsPanelStart >= 0, 'gui-v2 manga landing should keep the lower Details panel in the aside')
assert.ok(editorialChapterTableStart >= 0, 'gui-v2 manga landing should keep the editorial chapter table treatment')
assert.ok(landingProgressionPanelStart >= 0, 'gui-v2 manga landing should mark the chapter queue as a dedicated progression surface')
assert.ok(detailSource.includes("import LandingRecommendationsStage from './landing/LandingRecommendationsStage'"), 'manga landing should use the shared recommendations stage component')
assert.ok(detailSource.includes("import { useQuery } from '@tanstack/react-query'"), 'manga landing should use react-query for fallback recommendation enrichment')
assert.ok(detailSource.includes("const [chapterPage, setChapterPage] = useState(1)"), 'manga landing should track the current chapter page for long editorial queues')
assert.ok(detailSource.includes('buildLandingQueueWindow({'), 'manga landing should use the shared queue windowing helper')
assert.ok(landingPaginationStart >= 0, 'manga landing should render integrated editorial queue pagination controls')
assert.ok(detailSource.includes('const recommendationItems = useMemo(() => {'), 'manga landing should normalize recommendation-like arrays before rendering them')
assert.ok(detailSource.includes("const explicitRecommendationItems = useMemo(() => {"), 'manga landing should preserve native AniList recommendation arrays before falling back')
assert.ok(detailSource.includes('navigationEntry:'), 'manga landing recommendation cards should preserve enough AniList entry metadata to reopen the next title')
assert.ok(detailSource.includes('onRecommendationSelect = null'), 'manga landing should accept a recommendation-select callback from the parent route')
assert.equal(detailSource.indexOf("const recommendationSeedGenres = useMemo("), -1, 'manga landing should stop deriving genre fallback seeds once entry recommendations come directly from AniList')
assert.equal(detailSource.indexOf("const fallbackRecommendationsQuery = useQuery({"), -1, 'manga landing should not keep a genre fallback query once entry recommendations are AniList-only')
assert.equal(detailSource.indexOf("wails.discoverManga(recommendationSeedGenres.join(','), 0, 'POPULARITY_DESC', '', '', 1)"), -1, 'manga landing should not hydrate recommendation shelves from tag discovery when AniList entry recommendations exist')
assert.ok(detailSource.includes('recommendationsEmptyCopy'), 'manga landing should define empty-stage copy for the lower recommendations foundation')
assert.ok(landingRecommendationsStart > landingProgressionPanelStart, 'manga landing should reserve a lower recommendations continuation stage')
assert.ok(detailSource.includes('<LandingRecommendationsStage'), 'manga landing should mount a dedicated recommendations stage instead of raw inline facts')
assert.ok(detailSource.includes('items={recommendationItems}'), 'manga landing recommendations stage should receive normalized recommendation items')
assert.ok(detailSource.includes('onSelectItem={onRecommendationSelect}'), 'manga landing recommendations stage should delegate recommendation clicks back to the parent route')
assert.ok(detailSource.includes('emptyCopy={recommendationsEmptyCopy}'), 'manga landing recommendations stage should remain visible even before backend recommendation data is fully healthy')
assert.equal(detailSource.indexOf('copy={recommendationsCopy}'), -1, 'manga landing should not pass redundant helper copy into the recommendation shelf')
assert.equal(detailSource.indexOf('View all'), -1, 'manga landing should not render a purposeless View all action above characters')
assert.equal(detailSource.indexOf('Release Info'), -1, 'manga landing should not keep the old Release Info banner heading')
assert.equal(detailSource.indexOf("backgroundImage: `linear-gradient("), -1, 'manga landing hero should not inline the entire backdrop stack directly on the section')
assert.ok(detailSource.includes("'--gui2-landing-backdrop-image': `url(${selectedBanner})`"), 'manga landing should pass its banner art through a dedicated hero backdrop variable')
assert.equal(detailSource.indexOf('{ui.sourceTabsTitle}'), -1, 'manga landing should not keep the old boxed source stack in the aside')
assert.ok(mangaLandingHeroBlock, 'manga landing hero CSS block should exist')
assert.ok(landingWorkspaceBlock, 'landing workspace CSS block should exist')
assert.ok(landingPanelBlock, 'landing panel CSS block should exist')
assert.ok(immersiveLandingTopbarBlock, 'immersive landing topbar override block should exist')
assert.ok(css.includes(".gui2-landing-chapter-row {\n  padding: 14px;\n  border: 0;\n  border-radius: 0;\n  border-top: 1px solid rgba(255, 255, 255, 0.06);"), 'manga chapter rows should flatten into the shared room surface instead of boxed cards')
assert.ok(css.includes('.gui2-landing-panel--progression {'), 'progression landing panel CSS should exist')
assert.ok(css.includes('.gui2-landing-queue-pagination--editorial {'), 'manga landing should define CSS for editorial pagination alignment')
assert.ok(css.includes('.gui2-landing-recommendations {'), 'manga landing should define CSS for the lower recommendations stage')
assert.ok(css.includes('.gui2-landing-recommendations .gui2-landing-section-title {'), 'manga landing recommendation shelf should define a dedicated title treatment')
assert.ok(css.includes('.gui2-landing-recommendations-grid {'), 'manga landing should define a real recommendations card grid')
assert.ok(css.includes('.gui2-landing-recommendation-card {'), 'manga landing should define media-native recommendation cards')
assert.ok(css.includes('.gui2-landing-recommendation-card--placeholder {'), 'manga landing should define a warm placeholder foundation for missing recommendation data')
assert.ok(css.includes('.gui2-landing-fact-band {'), 'manga landing fact rows should flatten into a shared band instead of boxed cards')
assert.ok(css.includes('.gui2-landing-count {'), 'manga landing should use the shared inline count style')
assert.ok(mangaLandingHeroBlock[0].includes('min-height: clamp(500px, 43vw, 660px)'), 'manga landing hero should use the freed top space more assertively')
assert.ok(css.includes('background-position: center top, top right, center top;'), 'manga landing hero should anchor the banner art like a full stage instead of a repeated strip')
assert.ok(landingWorkspaceBlock[0].includes('margin-top: -44px'), 'manga landing workspace should connect more deeply back into the hero fade')
assert.ok(landingPanelBlock[0].includes('background: transparent'), 'manga landing sections should stop behaving like stacked shell slabs')
assert.ok(landingPanelBlock[0].includes('box-shadow: none'), 'manga landing sections should drop heavy stacked panel shadows')
assert.ok(immersiveLandingTopbarBlock[0].includes('backdrop-filter: none'), 'immersive landing topbar should not blur over manga hero art')

console.log('online manga detail layout tests passed')
