import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const detailPath = resolve(import.meta.dirname, './OnlineAnimeDetail.jsx')
const cssPath = resolve(import.meta.dirname, '../../gui-v2/styles/gui2.css')

const detailSource = readFileSync(detailPath, 'utf8')
const css = readFileSync(cssPath, 'utf8')
const landingHeroBlock = css.match(/^\s*\.gui2-landing-hero\s*\{[^}]+\}/m)
const landingWorkspaceBlock = css.match(/^\s*\.gui2-landing-workspace\s*\{[^}]+\}/m)
const landingEpisodeRowBlock = css.match(/^\s*\.gui2-landing-episode-row\s*\{[^}]+\}/m)
const landingPanelBlock = css.match(/^\s*\.gui2-landing-sidecard,\s*[\r\n]+\s*\.gui2-landing-panel\s*\{[^}]+\}/m)
const animeLandingHeroBlock = css.match(/^\s*\.gui2-landing-page--anime \.gui2-landing-hero\s*\{[^}]+\}/m)
const immersiveAnimeTopbarBlock = css.match(/^\s*\.gui2-shell\[data-shell-variant='immersive'\]\[data-route='anime-detail'\] \.gui2-topbar,\s*[\r\n]+\s*\.gui2-shell\[data-shell-variant='immersive'\]\[data-route='manga-detail'\] \.gui2-topbar\s*\{[^}]+\}/m)
const heroInlineBackdropPattern = /className="gui2-landing-hero gui2-landing-hero-premium"[\s\S]{0,240}backgroundImage:/m

const landingToolsStart = detailSource.indexOf('className="gui2-landing-section-tools gui2-landing-section-tools--wrap"')
const landingStreamingGroupStart = detailSource.indexOf('className="gui2-landing-tool-group gui2-landing-tool-group--stream"', landingToolsStart)
const landingPlaybackGroupStart = detailSource.indexOf('className="gui2-landing-tool-group gui2-landing-tool-group--playback"', landingToolsStart)
const landingToggleStart = detailSource.indexOf('className="episode-audio-toolbar episode-audio-toolbar--inline gui2-landing-audio-toolbar gui2-landing-tool-group"', landingToolsStart)
const landingPlaybackStart = detailSource.indexOf('className="episode-playback-switch gui2-landing-playback-toggle" aria-label={ui.playbackMode}', landingToolsStart)
const landingCountStart = detailSource.indexOf('className="gui2-landing-count"', landingToggleStart)
const landingFiltersStart = detailSource.indexOf('className="manga-filter-toggle" role="tablist" aria-label={t(\'Episodios\')}', landingToggleStart)
const sideAudioBlockStart = detailSource.indexOf('<h4 className="gui2-landing-mini-title">{ui.audioTrack}</h4>')
const landingQueueCopyStart = detailSource.indexOf('<p className="gui2-landing-section-copy">{ui.episodeQueueCopy}</p>')
const landingDetailsSidecardStart = detailSource.indexOf('<aside className="gui2-landing-sidecard">')
const landingProgressionPanelStart = detailSource.indexOf('className="gui2-landing-panel gui2-landing-panel--progression"')
const landingStreamFamilyStart = detailSource.indexOf('className="gui2-landing-stream-family"')
const landingFamilyToggleStart = detailSource.indexOf('className="gui2-landing-family-toggle" aria-label={ui.sourceAccess}', landingToolsStart)
const landingRecommendationsStart = detailSource.indexOf('<LandingRecommendationsStage')
const landingPaginationStart = detailSource.indexOf('className="gui2-landing-queue-pagination"')
const watchNavigatorStart = detailSource.indexOf('className="gui2-landing-panel gui2-landing-watchnav"')
const playerPageStart = detailSource.indexOf("className={`gui2-online-player-page${isWatchState ? ' gui2-online-player-page--active' : ''}`}")
const playerTitleBlockStart = detailSource.indexOf('className="gui2-online-player-copy"')
const pagePresentationStart = detailSource.indexOf('presentation="gui2-page"')
const watchStateHeroStart = detailSource.indexOf("className={`gui2-landing-hero gui2-landing-hero-premium${watchState === 'watch' ? ' gui2-landing-hero--watch' : ''}`}")
const warmupBatchStart = detailSource.indexOf('const episodesNeedingWarmup = useMemo(')
const watchWorkspaceStart = detailSource.indexOf("className={`gui2-landing-workspace${isWatchState ? ' gui2-landing-workspace--watch' : ''}`}")
const legacyToolbarPattern = /className="episode-audio-toolbar">\s*<div>\s*<div className="detail-stat-label"/

assert.ok(detailSource.includes("const [showFullSynopsis, setShowFullSynopsis] = useState(false)"), 'anime landing should track shortened synopsis state')
assert.ok(detailSource.includes("const [pendingIntegratedEpisode, setPendingIntegratedEpisode] = useState(null)"), 'anime landing should track a pending integrated episode while the stream resolves')
assert.ok(detailSource.includes("const [watchState, setWatchState] = useState('browse')"), 'anime landing should track browse vs watch state')
assert.ok(detailSource.includes("const [streamFamily, setStreamFamily] = useState('online')"), 'anime landing should track the selected streaming family inside the queue tools')
assert.ok(detailSource.includes("const [playbackMode, setPlaybackMode] = useState('mpv')"), 'anime landing should track the selected playback mode so in-app can be tested from the landing')
assert.ok(detailSource.includes("import LandingRecommendationsStage from './landing/LandingRecommendationsStage'"), 'anime landing should use the shared recommendations stage component')
assert.ok(detailSource.includes("const showIntegratedWatchState = isWatchState && Boolean(integratedPlayback?.url || pendingIntegratedEpisode)"), 'anime landing should derive a dedicated integrated watch-state gate for the stacked player room')
assert.ok(detailSource.includes("if (integratedPlayback?.url || pendingIntegratedEpisode) {"), 'anime landing should enter watch state as soon as in-app playback begins resolving')
assert.ok(detailSource.includes("const timeoutId = window.setTimeout(() => {"), 'anime landing should delay auto-scroll until the watch-state layout has settled')
assert.ok(detailSource.includes("requestAnimationFrame(() => {\n        requestAnimationFrame(runScroll)"), 'anime landing should wait for the player room to finish compositing before auto-scrolling')
assert.ok(detailSource.includes("liveTarget.scrollIntoView({ behavior: 'smooth', block: 'start' })"), 'anime landing should keep a smooth fallback scroll path for the player handoff')
assert.ok(detailSource.includes('const handleStreamFamilyChange = useCallback(async (targetFamily) => {'), 'anime landing should treat the stream-family switch as a live control in watch state')
assert.ok(detailSource.includes("const synopsisPreview = useMemo(() => {"), 'anime landing should derive a synopsis preview for the hero')
assert.ok(detailSource.includes('Read more'), 'anime landing should expose synopsis expansion interaction')
assert.equal(detailSource.indexOf('wails.warmOnlineEpisodeThumbnail('), -1, 'anime landing should not run the hidden thumbnail warm-up job from the detail surface anymore')
assert.equal(detailSource.indexOf("if (result?.status === 'scheduled')"), -1, 'anime landing should not poll scheduled thumbnail capture jobs from the landing page')
assert.equal(detailSource.indexOf('wails.prepareOnlineEpisodeThumbnail(payload)'), -1, 'anime landing should not request hidden stream-prep payloads for browser-side thumbnail capture')
assert.equal(detailSource.indexOf('captureThumbnailFromPreparedStream({'), -1, 'anime landing should not attempt hidden browser-side stream capture for episode thumbnails')
assert.equal(detailSource.indexOf('wails.persistOnlineEpisodeThumbnail({'), -1, 'anime landing should not persist browser-captured stills from the landing page')
assert.equal(detailSource.indexOf("import { EventsOn } from '../../../wailsjs/runtime/runtime'"), -1, 'anime landing should not depend on thumbnail warm-job events once capture-based enrichment is removed')
assert.equal(detailSource.indexOf("EventsOn('history:online-updated', () => {"), -1, 'anime landing should not subscribe to thumbnail warm-job history events once capture-based enrichment is removed')
assert.equal(detailSource.indexOf("wails.invalidateRuntimeCache(['online-episodes', anime.source_id, sourceAnimeID])"), -1, 'anime landing should not invalidate online-episodes runtime cache for removed capture warm jobs')
assert.equal(detailSource.indexOf('void episodesQuery.refetch()'), -1, 'anime landing should not refetch episodes solely to follow removed capture warm jobs')
assert.ok(detailSource.includes('const nextEpisodes = await wails.getOnlineEpisodes(anime.source_id, sourceAnimeID, 0)'), 'anime landing should read episodes through the standard metadata resolver instead of a force-fresh thumbnail capture path')
assert.ok(detailSource.includes('mergeEpisodeArtworkByNumber(nextEpisodes ?? [], anime.prefetchedEpisodes)'), 'anime landing should preserve early donor-enriched prefetched episode art when the authoritative backend episode list arrives')
assert.equal(detailSource.indexOf('const nextEpisodes = anime.prefetchedEpisodes?.length'), -1, 'anime landing should not short-circuit the episode query to prefetched shell episodes')
assert.ok(detailSource.includes("refetchOnMount: 'always'"), 'anime landing should revalidate its episode list on every remount in the live runtime')
assert.equal(detailSource.indexOf("Number(anime.episodes_watched || 0)"), -1, 'online anime detail should not use list progress as an episode-watch filter input')
assert.equal(detailSource.indexOf('const watchedFloor = Number(anime.episodes_watched || 0)'), -1, 'online anime detail should not derive a watched floor from anime list progress')
assert.equal(detailSource.indexOf("watched: Boolean(ep.watched) || ((Number(ep.number) || 0) > 0 && (Number(ep.number) || 0) <= watchedFloor)"), -1, 'online anime detail should not mark source episodes watched from anime list progress')
assert.equal(detailSource.indexOf('Promise.allSettled(episodesNeedingWarmup.map((ep) => warmEpisodeThumbnail(ep)))'), -1, 'anime landing should not keep the removed thumbnail warm-up batch orchestration')
assert.equal(detailSource.indexOf('for (let attempt = 0; attempt < 12; attempt += 1)'), -1, 'anime landing should not keep polling the removed capture warm-up loop')
assert.equal(detailSource.indexOf('let browserCaptureAttempts = 0'), -1, 'anime landing should not keep browser capture retry bookkeeping after the rollback')
assert.equal(detailSource.indexOf('browserCaptureAttempts < 3'), -1, 'anime landing should not retain browser capture retry limits after the rollback')
assert.ok(detailSource.includes('const recommendationItems = useMemo(() => {'), 'anime landing should normalize recommendation-like arrays into shared landing card data')
assert.ok(detailSource.includes("const explicitRecommendationItems = useMemo(() => {"), 'anime landing should preserve native AniList recommendation arrays before falling back')
assert.ok(detailSource.includes('navigationEntry:'), 'anime landing recommendation cards should preserve enough AniList entry metadata to reopen the next title')
assert.ok(detailSource.includes('onRecommendationSelect = null'), 'anime landing should accept a recommendation-select callback from the parent route')
assert.ok(detailSource.includes("const directTitle = typeof item?.title === 'string' ? item.title : ''"), 'anime landing should treat typed AniList recommendation titles as nested objects instead of stringifying them')
assert.equal(detailSource.indexOf("const recommendationSeedGenres = useMemo(() => {"), -1, 'anime landing should stop deriving genre fallback seeds once entry recommendations come directly from AniList')
assert.equal(detailSource.indexOf("const fallbackRecommendationsQuery = useQuery({"), -1, 'anime landing should not keep a genre fallback query once entry recommendations are AniList-only')
assert.equal(detailSource.indexOf("wails.discoverAnime(recommendationSeedGenres.join(','), '', 0, 'POPULARITY_DESC', '', '', 1)"), -1, 'anime landing should not hydrate recommendation shelves from tag discovery when AniList entry recommendations exist')
assert.ok(detailSource.includes('recommendationsEmptyCopy:'), 'anime landing should define empty-stage copy for the lower recommendations foundation')
assert.equal(detailSource.indexOf('View all'), -1, 'anime landing should not render a purposeless View all action above cast')
assert.ok(detailSource.includes("audioVariantProbeSources = new Set(['animegg-en', 'animepahe-en', 'animeav1-es'])"), 'audio variant probing should be ready for AnimeGG, AnimePahe, and AnimeAV1')
assert.ok(detailSource.includes('enabled: canProbeAudioVariants'), 'audio variant query should use the shared frontend probe gate')
assert.ok(detailSource.includes('const supportsAudioVariants = canProbeAudioVariants'), 'audio variant support should be driven by the shared frontend probe gate')
assert.ok(detailSource.includes('extractAniListAnimeSearchMedia(search)'), 'online anime detail should normalize AniList fallback search payloads instead of assuming a plain array response')
assert.ok(!detailSource.includes('const firstHit = Array.isArray(search) ? search[0] : null'), 'online anime detail should not assume searchAniList returns a plain array')
assert.ok(detailSource.includes("queryKey: ['anime-detail-anilist-v3', currentAniListID, lang]"), 'anime landing should keep the AniList detail query key stable while source resolution mutates the selected shell')
assert.equal(detailSource.indexOf('anime?.recommendations,'), -1, 'anime landing recommendations should not depend on the mutable selected shell payload once AniList detail is available')
assert.equal(detailSource.indexOf('anime?.related_recommendations,'), -1, 'anime landing recommendations should not depend on mutable related recommendation shell payloads')
assert.ok(!legacyToolbarPattern.test(detailSource), 'legacy standalone audio toolbar should not remain below the episode header')
assert.ok(landingToolsStart >= 0, 'gui-v2 landing episode tools should exist')
assert.ok(landingStreamingGroupStart > landingToolsStart, 'gui-v2 landing should separate the streaming family into its own tool group')
assert.ok(landingPlaybackGroupStart > landingStreamingGroupStart, 'gui-v2 landing should separate playback mode into a distinct group after streaming')
assert.ok(landingPlaybackStart > landingToolsStart, 'gui-v2 landing layout should render the playback-mode toggle inside the episode tools row')
assert.ok(landingPlaybackStart > landingFamilyToggleStart, 'gui-v2 landing should place playback mode after the streaming family control')
assert.ok(landingToggleStart > landingToolsStart, 'gui-v2 landing layout should render the audio toggle inside the episode tools row')
assert.ok(landingToggleStart > landingPlaybackStart, 'gui-v2 landing should place audio controls after playback mode')
assert.ok(landingCountStart > landingToggleStart, 'gui-v2 landing audio toggle should appear before the episode count and filter controls')
assert.ok(landingFiltersStart > landingToggleStart, 'gui-v2 landing audio toggle should appear before the episode filter buttons')
assert.equal(sideAudioBlockStart, -1, 'gui-v2 landing side panel should not render a standalone audio toggle block')
assert.equal(landingQueueCopyStart, -1, 'gui-v2 landing episode header should not render the legacy helper copy above the episode list')
assert.equal(landingDetailsSidecardStart, -1, 'gui-v2 landing hero should not render a duplicate Details sidecard above the episode list')
assert.ok(landingProgressionPanelStart >= 0, 'gui-v2 landing episode queue should opt into the dedicated progression surface treatment')
assert.ok(detailSource.includes("const [episodePage, setEpisodePage] = useState(1)"), 'anime landing should track the current episode page for long queues')
assert.ok(detailSource.includes('buildLandingQueueWindow({'), 'anime landing should use the shared queue windowing helper')
assert.equal(landingStreamFamilyStart, -1, 'anime landing should not keep the old dedicated source-access band between the hero and workspace')
assert.ok(landingFamilyToggleStart > landingToolsStart, 'anime landing should keep the stream-family toggle inside the landing tool rows instead of a separate source-access band')
assert.ok(landingPaginationStart >= 0, 'anime landing should render integrated queue pagination controls')
assert.ok(watchNavigatorStart > playerPageStart, 'anime landing should stage a dedicated watch navigator underneath the integrated player surface')
assert.ok(landingRecommendationsStart > landingProgressionPanelStart, 'anime landing should stage recommendations below the main landing workspace')
assert.ok(detailSource.includes('<LandingRecommendationsStage'), 'anime landing should always mount a dedicated recommendations stage instead of raw inline facts')
assert.ok(detailSource.includes('items={recommendationItems}'), 'anime landing recommendations stage should receive normalized recommendation items')
assert.ok(detailSource.includes('onSelectItem={onRecommendationSelect}'), 'anime landing recommendations stage should delegate recommendation clicks back to the parent route')
assert.ok(detailSource.includes('emptyCopy={ui.recommendationsEmptyCopy}'), 'anime landing recommendations stage should preserve a visible lower-stage foundation when recommendation data is missing')
assert.equal(detailSource.indexOf('copy={ui.recommendationsCopy}'), -1, 'anime landing should not pass redundant helper copy into the recommendation shelf')
assert.equal(detailSource.indexOf('role="tablist" aria-label={ui.sourceAccess}'), -1, 'anime landing should not advertise tabs when the stream-family control is only a button group')
assert.equal(detailSource.indexOf('<h3 className="gui2-landing-section-title">{ui.playbackMode}</h3>'), -1, 'anime landing should not render the old playback-mode side panel heading')
assert.equal(detailSource.indexOf('{ui.sourceSupportTitle}'), -1, 'anime landing should remove the Watching setup side rail completely')
assert.equal(detailSource.indexOf('Airing Info'), -1, 'anime landing should not keep the old Airing Info banner heading')
assert.ok(!heroInlineBackdropPattern.test(detailSource), 'anime landing hero should not inline the entire backdrop stack directly on the section')
assert.ok(detailSource.includes("'--gui2-landing-backdrop-image': `url(${backdropSrc})`"), 'anime landing should pass its banner art through a dedicated hero backdrop variable')
assert.ok(playerPageStart >= 0, 'gui-v2 online anime detail should define a dedicated in-app player page surface')
assert.ok(playerTitleBlockStart > playerPageStart, 'gui-v2 player page should render its title block inside the dedicated player surface')
assert.ok(pagePresentationStart > 0, 'integrated player should support a gui-v2 page presentation mode')
assert.ok(watchStateHeroStart >= 0, 'anime landing hero should compress in watch state')
assert.equal(warmupBatchStart, -1, 'anime landing should not derive a landing-page thumbnail warm-up batch after the rollback')
assert.ok(detailSource.includes('if (!hasZeroThumbnailCoverage(episodes)) return'), 'anime landing fallback enrichment should only run when the active episode list still has zero thumbnail coverage')
assert.ok(watchWorkspaceStart >= 0, 'anime landing workspace should adapt once the player is active')
assert.ok(!detailSource.includes('ui.integratedNote'), 'legacy Anime4K helper copy should not be rendered in the online anime detail layout')
assert.ok(css.includes('.episode-toolbar-actions {'), 'episode toolbar actions CSS should exist')
assert.ok(css.includes('.episode-audio-toolbar--inline {'), 'inline audio toolbar CSS should exist')
assert.ok(css.includes('.episode-audio-toolbar-label {'), 'inline audio label CSS should exist')
assert.ok(css.includes('.gui2-landing-panel--progression {'), 'progression landing panel CSS should exist')
assert.ok(css.includes('.gui2-online-player-page {'), 'gui-v2 online player page CSS should exist')
assert.ok(css.includes('.gui2-online-player-page--active {'), 'anime landing should define an active watch-surface player stage')
assert.ok(css.includes('.gui2-online-player-loading {'), 'anime landing should define an integrated-player loading stage for the immediate watch-state handoff')
assert.ok(css.includes('.integrated-player-overlay--page {'), 'integrated player page presentation CSS should exist')
assert.ok(css.includes('.integrated-player-shell--page {'), 'integrated player page shell CSS should exist')
assert.ok(css.includes('.gui2-landing-family-toggle {'), 'anime landing should define CSS for the streaming family toggle')
assert.ok(css.includes('.gui2-landing-family-btn {'), 'anime landing should define CSS for the streaming family buttons')
assert.ok(css.includes('.gui2-landing-tool-group {'), 'anime landing should define grouped queue-tool spacing so streaming and player mode stop reading as one merged control')
assert.ok(css.includes('.gui2-landing-tool-label {'), 'anime landing should define a small cue label for each queue-tool group')
assert.ok(css.includes('.gui2-landing-playback-toggle {'), 'anime landing should define CSS for the inline playback mode switch')
assert.ok(css.includes('.gui2-landing-fact-band {'), 'landing facts should flatten into a shared band instead of boxed cards')
assert.ok(css.includes('.gui2-landing-count {'), 'landing controls should expose a dedicated inline count style')
assert.ok(css.includes('.gui2-landing-queue-pagination {'), 'anime landing queue pagination CSS should exist')
assert.ok(css.includes('.gui2-landing-pagechip {'), 'anime landing queue page-chip CSS should exist')
assert.ok(css.includes('.gui2-landing-recommendations {'), 'anime landing should define CSS for the lower recommendations stage')
assert.ok(css.includes('.gui2-landing-recommendations .gui2-landing-section-title {'), 'anime landing recommendation shelf should define a dedicated title treatment')
assert.ok(css.includes('.gui2-landing-recommendations-grid {'), 'anime landing should define a real recommendations card grid')
assert.ok(css.includes('.gui2-landing-recommendation-card {'), 'anime landing should define media-native recommendation cards')
assert.ok(css.includes('.gui2-landing-recommendation-card--placeholder {'), 'anime landing should define a warm placeholder foundation for missing recommendation data')
assert.ok(css.includes('.gui2-landing-watchnav {'), 'anime landing should define CSS for the dedicated watch-state episode navigator')
assert.ok(css.includes('.gui2-landing-watchnav-grid {'), 'anime landing should define CSS for the large watch-state episode grid')
assert.ok(css.includes('.gui2-landing-watchcard {'), 'anime landing should define CSS for the watch-state episode cards')
assert.ok(css.includes('.gui2-landing-hero--watch {'), 'anime landing should define a compressed watch-state hero')
assert.ok(css.includes('.gui2-landing-workspace--watch {'), 'anime landing workspace should adapt once the player is active')
assert.ok(css.includes('.gui2-landing-hero-grid--watch {'), 'anime landing should define a tighter hero grid for integrated watch state')
assert.ok(css.includes('@keyframes gui2WatchSurfaceIn {'), 'anime landing should animate the watch-surface transition instead of hard-swapping it')
assert.ok(landingHeroBlock, 'shared landing hero CSS block should exist')
assert.ok(landingWorkspaceBlock, 'shared landing workspace CSS block should exist')
assert.ok(landingEpisodeRowBlock, 'landing episode row CSS block should exist')
assert.ok(landingPanelBlock, 'landing panel CSS block should exist')
assert.ok(animeLandingHeroBlock, 'anime landing hero CSS block should exist')
assert.ok(immersiveAnimeTopbarBlock, 'immersive landing routes should define a dedicated topbar override block')
assert.ok(landingHeroBlock[0].includes('margin-top: calc(var(--gui2-topbar-h) * -1)'), 'landing hero should bleed upward under immersive shell chrome')
assert.ok(landingHeroBlock[0].includes('overflow: hidden'), 'landing hero should clip the backdrop like a room stage instead of a flat band')
assert.ok(landingHeroBlock[0].includes('background-repeat: no-repeat'), 'landing hero should prevent backdrop tiling when a real banner is available')
assert.ok(landingHeroBlock[0].includes("background-image:"), 'landing hero should own its backdrop composition in CSS')
assert.ok(landingWorkspaceBlock[0].includes('position: relative'), 'landing workspace should anchor itself to the hero as one connected field')
assert.ok(landingWorkspaceBlock[0].includes('margin-top: -44px'), 'landing workspace should climb more deeply into the hero fade instead of dropping into a detached layout')
assert.ok(landingEpisodeRowBlock[0].includes('border-top: 1px solid rgba(255, 255, 255, 0.06)'), 'anime episode rows should flatten into the shared room surface instead of boxed cards')
assert.ok(landingPanelBlock[0].includes('background: transparent'), 'landing sections should stop behaving like heavy stacked slabs')
assert.ok(landingPanelBlock[0].includes('box-shadow: none'), 'landing sections should drop the heavy stacked panel shadows')
assert.ok(animeLandingHeroBlock[0].includes('min-height: clamp(560px, 48vw, 760px)'), 'anime landing hero should use the freed frameless top space more like Home')
assert.ok(immersiveAnimeTopbarBlock[0].includes('backdrop-filter: none'), 'immersive landing topbar should not blur over the hero art')

console.log('online anime detail layout tests passed')
